new element abilites
lucasGithuber/Element-Manipulation pull request #5
Opened 2022-08-11 16:26 UTC by TerslenK

yknow what it is

2022-08-11 16:26 UTC, TerslenK commented
this is only potassium for now

ill add more if you tell me what element does

2022-08-17 19:53 UTC, lucasGithuber requested changes
wowie

2022-08-17 19:54 UTC, lucasGithuber approved these changes

2022-08-17 19:58 UTC, lucasGithuber requested changes
idk how to push commits into a pr via github dev

2022-08-17 19:58 UTC, lucasGithuber approved these changes

2022-08-17 20:12 UTC, merged